Repository buildpacks/github-actions, pull requests merged in 2020-11, with the labels that each got.

#3 Added action.yml and pack.sh
  README.md
  setup-pack/action.yml
Labels: semver:major, type:enhancement

#4 Buildpack Info Action
  .github/workflows/create-action-buildpack-info.yml
  README.md
  go.mod
  go.sum
  info/buildpack_info.go
  info/buildpack_info_test.go
  info/cmd/main.go
  info/testdata/buildpack.toml
Labels: semver:major, type:enhancement

#6 Update Pipelines Workflow
  .github/pipeline-descriptor.yml
  .github/workflows/update-pipeline.yml
Labels: semver:patch, type:task

#8 GitHub Token
  .github/pipeline-descriptor.yml
  .github/workflows/create-action-buildpack-info.yml
  .github/workflows/create-action-registry.yml
  .github/workflows/synchronize-labels.yml
  .github/workflows/update-draft-release.yml
  .github/workflows/update-pipeline.yml
Labels: semver:patch, type:task

#5 Add verify-package image
  .github/workflows/create-verify-buildpackage-action.yml
  README.md
  go.mod
  go.sum
  verify/cmd/main.go
  verify/verify.go
  verify/verify_test.go
Labels: semver:major, type:enhancement

#12 Update README.md
  README.md
Labels: semver:patch, type:documentation

#15 Pack 0.15.0
  setup-pack/action.yml
Labels: semver:minor, type:dependency-upgrade
