Repository buildpacks/github-actions, pull requests merged in 2021-07, with the labels that each got.

#68 adds workflow to trigger creation of PR in buildpacks/registry-index and fixes #40
  .github/workflows/action-registry-index-update-release.yml
Labels: semver:patch, type:task

#69 fixes version of repository-dispatch back to v1
  .github/workflows/action-registry-index-update-release.yml
Labels: semver:patch, type:bug

#71 Update default Pack version from 0.17.0 to 0.20.0
  setup-pack/action.yml
Labels: semver:minor, type:dependency-upgrade
